[package]
name = "clfft"
version = "0.2.0"
authors = ["Christian Liebhardt"]
build = "build.rs"
license = "Apache-2.0"
homepage = "https://github.com/liebharc/clfft"
repository = "https://github.com/liebharc/clfft"
documentation = "http://clmathlibraries.github.io/clFFT/"
keywords = ["fft", "opencl"]
description = "Bindings for clFFT, a FFT library for OpenCL."

[lib]
crate-type = ["rlib"]

[dependencies]
ocl = "^0.12.0"
lazy_static = "^0.2.0"

[features]
build_all = ["cmake"]

[build-dependencies]
cmake = { version = "^0.1.0", optional = true }

[dev-dependencies]
rustfft = "^1.0.0"
num = "^0.1.34"