[package]
name = "clfft"
version = "0.1.0"
authors = ["Christian Liebhardt"]
build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
ocl = "^0.12.0"


[features]
build_all = ["cmake"]

[build-dependencies]
cmake = { version = "^0.1.0", optional = true }